### ISSUE TITLE
Logos are empty !

### ISSUE THREAD

**Issue by bourgesl** [foojayio/badges#2]
It seems current logos are empty !

See https://raw.githubusercontent.com/foojayio/badges/main/works_with_openjdk/Works-with-OpenJDK.png

**Comment by geertjanw** [comment]
yes, we’re rethinking this campaign at the moment and will come back with a different image soon.

**Comment by bourgesl** [comment]
Is it legally ok that I hacked your logo using sep 29th version ?
See https://github.com/bourgesl/bourgesl.github.io/blob/master/marlin-badge-xmas-2021/WorksWithOpenJDK-Marlin-powered-512.png

**Comment by geertjanw** [comment]
Would be good to take it down for the moment, we'll come back with something better soon. :-)
